name: Flutter CI/CD

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the workflow on

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.4'  # You can specify the Flutter version you want

    - name: Change to Flutter project directory
      run: cd frontend

    - name: Set Dart SDK version
      run: flutter --version

    - name: Get dependencies
      run: flutter pub get
      working-directory: frontend  

    - name: Analyze code
      run: flutter analyze
      working-directory: frontend  

    - name: Run tests
      run: flutter test
      working-directory: frontend  

  release:
    name: Release APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.4'

    - name: Get dependencies
      run: flutter pub get
      working-directory: frontend 

    - name: Change gradle version
      run: sed -i 's/org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50/org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.20/g' android/build.gradle  # Update Kotlin version
      working-directory: frontend 

      
    - name: Build APK
      run: flutter build apk --release
      working-directory: frontend 

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
